In [1]:
# Importing required modules
import pandas as pd
from sqlalchemy import inspect, create_engine

In [2]:
# Location of csv documents
Cad_trending_loc = "CSV files/CAvideos.csv"
Subscribers_loc = "CSV files/channels.csv"

In [3]:
# Reading csv files using pandas
cad_trend = pd.read_csv(Cad_trending_loc)
subscribers = pd.read_csv(Subscribers_loc)

In [4]:
# Cleaning Data for trending videos
cad_trend = cad_trend[["channel_title","title", "category_id","views","likes","dislikes","comment_count"]]
cad_trend.head()

,channel_title,title,category_id,views,likes,dislikes,comment_count
0,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,17158579,787425,43420,125882
1,iDubbbzTV,PLUSH - Bad Unboxing Fan Mail,23,1014651,127794,1688,13030
2,Rudy Mancuso,"Racist Superman | Rudy Mancuso, King Bach & Le...",23,3191434,146035,5339,8181
3,nigahiga,I Dare You: GOING BALD!?,24,2095828,132239,1989,17518
4,Ed Sheeran,Ed Sheeran - Perfect (Official Music Video),10,33523622,1634130,21082,85067

In [5]:
# Changing column names
cad_trend.rename(columns = {"channel_title": "Channel Name", "title": "Video Name", "category_id":"Category ID",\
                           "views":"Views","likes":"Likes","dislikes":"Dislikes","comment_count":\
                            "Number of Comments"},inplace = True)
cad_trend.head()

,Channel Name,Video Name,Category ID,Views,Likes,Dislikes,Number of Comments
0,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,17158579,787425,43420,125882
1,iDubbbzTV,PLUSH - Bad Unboxing Fan Mail,23,1014651,127794,1688,13030
2,Rudy Mancuso,"Racist Superman | Rudy Mancuso, King Bach & Le...",23,3191434,146035,5339,8181
3,nigahiga,I Dare You: GOING BALD!?,24,2095828,132239,1989,17518
4,Ed Sheeran,Ed Sheeran - Perfect (Official Music Video),10,33523622,1634130,21082,85067

In [6]:
# Cleaning Data for subscribers videos
subscribers = subscribers[["title","category_name","followers","videos"]]
subscribers.head()

             title  category_name  followers  videos
0        PewDiePie  Entertainment   69896406    3649
1         T-Series          Music   69471946   12820
2    Justin Bieber  Entertainment   41858494     132
3  5-Minute Crafts  Howto & Style   40474509    2350
4              WWE         Sports   36301947   37928

In [7]:
# Changing column names
subscribers.rename(columns = {"title": "Channel Name","category_name":"Category Name",\
                              "followers":"Followers", "videos": "Number of Videos"},inplace = True)
subscribers.head()

      Channel Name  Category Name  Followers  Number of Videos
0        PewDiePie  Entertainment   69896406              3649
1         T-Series          Music   69471946             12820
2    Justin Bieber  Entertainment   41858494               132
3  5-Minute Crafts  Howto & Style   40474509              2350
4              WWE         Sports   36301947             37928

In [8]:
# Merging documents
Youtube = pd.merge(cad_trend,subscribers, on ="Channel Name")
Youtube.head()

,Channel Name,Video Name,Category ID,Views,Likes,Dislikes,Number of Comments,Category Name,Followers,Number of Videos
0,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,17158579,787425,43420,125882,Music,26572348,82
1,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,20539417,840642,47715,124236,Music,26572348,82
2,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,22702386,869304,50018,123235,Music,26572348,82
3,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,24578152,891283,51978,125444,Music,26572348,82
4,EminemVEVO,Walk On Water/Stan/Love The Way You Lie (Medle...,10,1535199,153770,2439,16875,Music,26572348,82

# Connect to local database

In [9]:
# Connect to local data base
rds_connection_string = "postgres:postgres@localhost:5432/youtube_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [10]:
# Engine table name
engine.table_names()

['youtube']

In [11]:
# Use pandas to load database into pgAdmin server
Youtube.to_sql(name='youtube', con=engine, if_exists='append', index=False)

In [12]:
# Making sure data is imported
pd.read_sql_query('select * from youtube', con=engine).head()

,Channel Name,Video Name,Category ID,Views,Likes,Dislikes,Number of Comments,Category Name,Followers,Number of Videos
0,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,17158579,787425,43420,125882,Music,26572348,82
1,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,20539417,840642,47715,124236,Music,26572348,82
2,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,22702386,869304,50018,123235,Music,26572348,82
3,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,10,24578152,891283,51978,125444,Music,26572348,82
4,EminemVEVO,Walk On Water/Stan/Love The Way You Lie (Medle...,10,1535199,153770,2439,16875,Music,26572348,82